package dbsheme

const GGroupsSrc = `
CREATE TABLE "ggroups_src" (
"ID"	INTEGER NOT NULL UNIQUE,
"Rid"	INTEGER NOT NULL UNIQUE,
"Guid"	TEXT NOT NULL,
"FIELD_42"	TEXT NOT NULL,
"Name"	TEXT NOT NULL,
"Attr"	TEXT NOT NULL,
"Rid_PARENT"	INTEGER NOT NULL,
"Guid_PARENT"	TEXT NOT NULL,
"FIELD_42_PARENT"	INTEGER NOT NULL,
"Name_PARENT"	TEXT NOT NULL,
"Attr_PARENT"	TEXT NOT NULL,
"UserGroup"	INTEGER NOT NULL,
"Rid_106"	INTEGER NOT NULL,
"Name_106"	TEXT NOT NULL,
"Action" TEXT NOT NULL,
PRIMARY KEY("ID" AUTOINCREMENT));
`

const GGroupsDst = `
CREATE TABLE "ggroups_dst" (
"ID"	INTEGER NOT NULL UNIQUE,
"Rid"	INTEGER NOT NULL UNIQUE,
"Guid"	TEXT NOT NULL,
"FIELD_42"	TEXT NOT NULL,
"Name"	TEXT NOT NULL,
"Attr"	TEXT NOT NULL,
"Rid_PARENT"	INTEGER NOT NULL,
"Guid_PARENT"	TEXT NOT NULL,
"FIELD_42_PARENT"	INTEGER NOT NULL,
"Name_PARENT"	TEXT NOT NULL,
"Attr_PARENT"	TEXT NOT NULL,
"UserGroup"	INTEGER NOT NULL,
"Rid_106"	INTEGER NOT NULL,
"Name_106"	TEXT NOT NULL,
"Action" TEXT NOT NULL,
PRIMARY KEY("ID" AUTOINCREMENT));
`
